services:
    postgres_db:
        container_name: postgres_db
        image: postgres:15
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            APP_USER: ${APP_USER}
            APP_PASSWORD: ${APP_PASSWORD}
            AF_USER: ${AF_USER}
            AF_PASSWORD: ${AF_PASSWORD}
        ports:
            - "5000:5432"
        networks:
            - data-pipeline
        volumes:
            - ./infra/postgres/data:/var/lib/postgresql/data
            - ./infra/postgres/init:/docker-entrypoint-initdb.d
        

    mongo_db:
        container_name: mongo_db
        build:
            context: ./infra/mongo
            dockerfile: mongo.Dockerfile
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            APP_USER: ${APP_USER}
            APP_PASSWORD: ${APP_PASSWORD}
        ports:
            - "27017:27017"
        networks:
            - data-pipeline
        volumes:
            - ./infra/mongo/data:/data/db

    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - data-pipeline


networks:
    data-pipeline:
        driver: bridge
